swagger:
  base-package: me.robin.crawler.web
  api-info:
    version: 1.0
    title: ${spring.application.name}
    description: 爬虫控制
  contact:
    name: Lubin.Xuan
    email: lubin.xuan@gmail.com
server:
  port: 9999
spring:
  application:
    name: crawler
  datasource:
    url: jdbc:h2:tcp://192.168.5.5:9092/lite_crawler;MODE=MySQL
    username: crawler
    password: X900907
    driver-class-name: org.h2.Driver
chromeBin: C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
spiders: config/wdzj.json|config/p2peye.json