swagger:
  base-package: me.robin.crawler.web
  api-info:
    version: 1.0
    title: ${spring.application.name}
    description: 爬虫控制
  contact:
    name: Lubin.Xuan
    email: lubin.xuan@gmail.com
server:
  port: 9999
spring:
  application:
    name: crawler
  redis:
    host: 127.0.0.1
    port: 16380
    database: 1
chromeBin: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
spiders: config/wdzj.json|config/p2peye.json
push:
  host: 127.0.0.1
  port: 8080